# Generated by Django 5.2 on 2025-05-04 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hostel_management_user_student_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='grad_year',
            new_name='admn_year',
        ),
    ]
