# Generated by Django 5.2 on 2025-05-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_grad_year_student_admn_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelroom',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
