# Generated by Django 5.2 on 2025-05-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hostelroom_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelroom',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default='m', max_length=1),
        ),
    ]
