# Generated by Django 5.2 on 2025-05-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hostelroom_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelroom',
            name='gender',
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default='m', max_length=1),
        ),
    ]
