# Generated by Django 5.2 on 2025-05-09 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_hostelroom_gender_student_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_s', models.BooleanField(default=False)),
                ('fan_c', models.BooleanField(default=False)),
                ('tube_light_s', models.BooleanField(default=False)),
                ('tube_light_c', models.BooleanField(default=False)),
                ('fan_regulator_s', models.BooleanField(default=False)),
                ('fan_regulator_c', models.BooleanField(default=False)),
                ('switch_board_s', models.BooleanField(default=False)),
                ('switch_board_c', models.BooleanField(default=False)),
                ('cupboard_s_s', models.BooleanField(default=False)),
                ('cupboard_s_c', models.BooleanField(default=False)),
                ('cupboard_safe_s', models.BooleanField(default=False)),
                ('cupboard_safe_c', models.BooleanField(default=False)),
                ('book_rack_s', models.BooleanField(default=False)),
                ('book_rack_c', models.BooleanField(default=False)),
                ('writing_table_s', models.BooleanField(default=False)),
                ('writing_table_c', models.BooleanField(default=False)),
                ('chair_s', models.BooleanField(default=False)),
                ('chair_c', models.BooleanField(default=False)),
                ('door_s', models.BooleanField(default=False)),
                ('door_c', models.BooleanField(default=False)),
                ('door_lock_s', models.BooleanField(default=False)),
                ('door_lock_c', models.BooleanField(default=False)),
                ('window_shutters_s', models.BooleanField(default=False)),
                ('window_shutters_c', models.BooleanField(default=False)),
                ('window_panes_s', models.BooleanField(default=False)),
                ('window_panes_c', models.BooleanField(default=False)),
                ('bed_s', models.BooleanField(default=False)),
                ('bed_c', models.BooleanField(default=False)),
                ('mattress_s', models.BooleanField(default=False)),
                ('mattress_c', models.BooleanField(default=False)),
                ('walls_s', models.BooleanField(default=False)),
                ('walls_c', models.BooleanField(default=False)),
                ('hot_air_regulator_s', models.BooleanField(default=False)),
                ('hot_air_regulator_c', models.BooleanField(default=False)),
                ('allow_edit', models.BooleanField(default=True)),
                ('filled_by_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_forms', to='core.student')),
                ('hostel_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_forms', to='core.hostelroom')),
            ],
        ),
    ]
