# Generated by Django 5.2 on 2025-05-10 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_inventoryform'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('swap', 'Swap Rooms'), ('change', 'Change Room')], max_length=10)),
                ('approved_for_apply', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('priority_total', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to=models.Q(('role__in', ['warden', 'chief_warden'])), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_change_requests_approved', to='core.hostel_management')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_requests', to='core.student')),
                ('requested_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_requests', to='core.student')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hostelroom')),
            ],
        ),
    ]
