"""
Django settings for facilitator project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&ic(*1-di)%0tdaw+0!82ubk_g8nn&g!en1w=y0mgpz#p7%62%'
KEYCLOAK_PUBLIC_KEY = """
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAokUDM6nAsR6/w4jDBaMg
k9XfX0zx3yl+KDGWvilF1Cg20B3kQxkm5jjMd+3gqm9p76E1UbRRj6CstBaxjDjH
5j+DSHyL91nXDXRCe14SpUou2YIimIEHrv++YoPdSHbIq9Z53spy0gKyUVdM1XWM
r9gLaSYQlMOXVNGgBZq64uTo5+4R0iSRN9+z8XOgzIT7tWGT2yoJILHuvgwY32L6
+700FDPlGLjRTVRiClN6sIUW5NU/ioFsNYuzp4Vf19RX/4W0CbKlv7VV5T/R3+pz
s+tUGz48RBIrmbcpWsoh3xv0ZTBG/Y4zuJ5uQ2raCYAfDj4eKJxUTFSW5u2ZEFKm
CwIDAQAB
-----END PUBLIC KEY-----
"""


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
CORS_ALLOW_ALL_ORIGINS = True

AUTH_USER_MODEL = 'auth_service.CustomUser'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'auth_service',
    'chatbot_service',
    'notify_service',
    'corsheaders',
    # 'django_keycloak.apps.KeycloakAppConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'django_keycloak.middleware.KeycloakMiddleware',  # Keycloak Middleware
    # 'django_keycloak.middleware.BaseKeycloakMiddleware',
    'auth_service.middleware.KeycloakTokenMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

# Keycloak settings for Django
AUTHENTICATION_BACKENDS = [
    # 'django_keycloak.auth.backends.KeycloakAuthorizationCodeBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# LOGIN_URL = 'keycloak_login'

KEYCLOAK_SERVER_URL = 'http://localhost:8080/'
KEYCLOAK_REALM = 'Ashrey'
KEYCLOAK_CLIENT_ID = 'ashrey-manager-client'
KEYCLOAK_CLIENT_SECRET = "zn2bjfBgLrqKDj9D5RoBZ3aTUTljn2Qc"
KEYCLOAK_REDIRECT_URI = 'http://localhost:8081/callback/'
LOGOUT_REDIRECT_URL = 'http://localhost:8081/'
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = 'http://localhost:8081/home/' 

# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",
#     "http://localhost:3000",  # React app URL
# ]

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True

# PASSWORD_HASHERS = [
#     'django_keycloak.hashers.PBKDF2SHA512PasswordHasher',
# ]

# Set redirect URIs and other Keycloak settings as needed
KEYCLOAK_CONFIG = {
    'OIDC_USERINFO_URL': f'{KEYCLOAK_SERVER_URL}/realms/{KEYCLOAK_REALM}/protocol/openid-connect/userinfo',
    'OIDC_TOKEN_URL': f'{KEYCLOAK_SERVER_URL}/realms/{KEYCLOAK_REALM}/protocol/openid-connect/token',
    'OIDC_AUTHORIZE_URL': f'{KEYCLOAK_SERVER_URL}/realms/{KEYCLOAK_REALM}/protocol/openid-connect/auth',
}

ROOT_URLCONF = 'facilitator.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'facilitator.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'