# Generated by Django 5.2 on 2025-05-03 13:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('Hname', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('amenities', models.TextField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'Hname'), name='unique_hostel_name')],
            },
        ),
        migrations.CreateModel(
            name='HostelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.SmallIntegerField()),
                ('capacity', models.SmallIntegerField(default=2)),
                ('occupancy', models.SmallIntegerField(default=0)),
                ('priority_score', models.FloatField(default=0.0)),
                ('floor', models.IntegerField(default=2)),
                ('level', models.IntegerField(default=-10)),
                ('balcony', models.BooleanField(default=False)),
                ('sunny', models.BooleanField(default=False)),
                ('hostel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.hostels')),
            ],
        ),
        migrations.CreateModel(
            name='Hostel_Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ph_number', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('email', models.EmailField(default='', max_length=254)),
                ('role', models.CharField(choices=[('guard', 'Guard'), ('warden', 'Warden'), ('chief_warden', 'Chief Warden'), ('caretaker', 'Caretaker')], default='warden', max_length=50)),
                ('hostel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.hostels')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=21)),
                ('enroll_number', models.IntegerField(unique=True)),
                ('email', models.EmailField(default='', max_length=254)),
                ('student_contact', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('parent_contact1', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('parent_contact2', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('alloted', models.BooleanField(default=False)),
                ('cg', models.FloatField(default=0.0)),
                ('year', models.IntegerField()),
                ('priority_score', models.FloatField(default=0.0)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='services.hostelroom')),
            ],
        ),
        migrations.AddConstraint(
            model_name='hostelroom',
            constraint=models.CheckConstraint(condition=models.Q(('level__gte', -13), ('level__lte', 5)), name='level_range'),
        ),
        migrations.AddConstraint(
            model_name='hostelroom',
            constraint=models.UniqueConstraint(fields=('room_number',), name='unique_room_number'),
        ),
    ]
