# Generated by Django 5.2 on 2025-05-03 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hostels',
            name='unique_hostel_name',
        ),
        migrations.RemoveField(
            model_name='hostels',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hostels',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='hostels',
            name='capacity',
        ),
    ]
