# Generated by Django 5.2 on 2025-05-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_rename_year_student_grad_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelroom',
            name='room_number',
            field=models.IntegerField(default=0),
        ),
    ]
