# Generated by Django 5.2 on 2025-05-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_hostelroom_room_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hostelroom',
            name='unique_room_number',
        ),
        migrations.AlterField(
            model_name='hostelroom',
            name='room_number',
            field=models.SmallIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='hostelroom',
            constraint=models.UniqueConstraint(fields=('room_number', 'hostel'), name='unique_room_in_hostel'),
        ),
    ]
