# Generated by Django 5.2 on 2025-05-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_hostelroom_unique_room_number_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hostelroom',
            name='unique_room_in_hostel',
        ),
        migrations.AddField(
            model_name='student',
            name='hosteller',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hostelroom',
            name='room_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='hostelroom',
            constraint=models.UniqueConstraint(fields=('room_number', 'hostel'), name='unique_room_per_hostel'),
        ),
    ]
