# Generated by Django 5.2 on 2025-05-03 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_hostelroom_unique_room_in_hostel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outpass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('reason', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_of_leave', models.PositiveIntegerField(default=0)),
                ('approvedcheck', models.BooleanField(default=False)),
                ('markout', models.BooleanField(default=False)),
                ('markin', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to=models.Q(('role__iexact', 'warden'), ('role__iexact', 'chief warden'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_outpasses', to='services.hostel_management')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.student')),
            ],
        ),
    ]
