# Generated by Django 5.2 on 2025-05-03 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_outpass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outpass',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('role__iexact', 'warden'), ('role__iexact', 'chief_warden'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_outpasses', to='services.hostel_management'),
        ),
    ]
