# Generated by Django 5.2 on 2025-05-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_outpass_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpass',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
